name: drdr.xp Blog
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
# markdown: redcarpet
highlighter: pygments
paginate: 20
description: xp's idea

author:  'drdr.xp'
weibo_uid: 'drdrxp'
url:     'http://drmingdrmer.github.io'
baseurl: '/'
email:   'drdr.xp@gmail.com'
aboutme: 'Software Engineer at Sina'

gems:
    - jemoji
