name: drdr.xp Blog
markdown: kramdown
highlighter: pygments
paginate: 3
description: xp's idea

author:  'drdr.xp'
url:     'http://drmingdrmer.github.io'
baseurl: '/'
email:   'drdr.xp@gmail.com'
aboutme: 'Software Engineer at Sina'

gems:
    - jemoji
