# Install dependency
# gem install jekyll-paginate



name:     drdr.xp Blog
markdown: kramdown
# markdown: redcarpet
kramdown:
    input: GFM
    hard_wrap: false
highlighter: rouge
paginate:    20
description: xp's idea

author:    'drdr.xp'
weibo_uid: 'drdrxp'
url:       'https://drmingdrmer.github.io'
baseurl:   '/'
email:     'drdr.xp@gmail.com'
aboutme:   'VP of Engineering at Baishancloud.com'

plugins:
    - jekyll-paginate
    - jekyll-feed
    # - jemoji
