name: drdr.xp Blog
markdown: redcarpet
highlighter: pygments
paginate: 3
description: xp's idea

author:  'drdr.xp'
url:     'http://drmingdrmer.github.io'
email:   'drdr.xp@gmail.com'
aboutme: 'Software Engineer at Sina'
